const books = [
    // ── Featured Homepage books(1->4)
    {
        id: 1,
        img: "img/avenger-mighty.png",
        category: "Comic",
        title: "Avengers: Mighty Heroes",
        author: "Sophea Reaksa",
        style: "architecture",
        status: "Available",
        description: "Earth's mightiest heroes unite in this action-packed comic collection. Follow Iron Man, Captain America, Thor, and the rest of the Avengers as they face cosmic threats, internal conflicts, and the timeless question of what it truly means to be a hero.",
        published: "2024",
        pages: "320",
        language: "English",
        isbn: "978-3-16-148410-9",
        rating: "4.8",
        reviews: "128",
        badge: "available"
    },
    {
        id: 2,
        img: "img/doctor-strange.png",
        category: "Comic",
        title: "Doctor Strange",
        author: "Sok Chanleap",
        style: "sociology",
        status: "Available",
        description: "Journey into the mystical arts with the Sorcerer Supreme. Doctor Strange protects our reality from interdimensional threats while wrestling with the cost of power and the boundaries of knowledge.",
        published: "2023",
        pages: "280",
        language: "English",
        isbn: "978-3-16-148410-10",
        rating: "4.7",
        reviews: "96",
        badge: "available"
    },
    {
        id: 3,
        img: "img/iron-man.png",
        category: "Comic",
        title: "Iron-Man",
        author: "StickyDoughTwist",
        style: "acoustics",
        status: "Borrowed",
        description: "The armored Avenger faces his greatest technological threats. Tony Stark must out-engineer his enemies and his own inner demons in this high-stakes comic adventure.",
        published: "2024",
        pages: "300",
        language: "English",
        isbn: "978-3-16-148410-11",
        rating: "4.6",
        reviews: "84",
        badge: "borrowed"
    },
    {
        id: 4,
        img: "img/spider-man.png",
        category: "Comic",
        title: "Spider-Man",
        author: "Zodiac",
        style: "architecture",
        status: "Available",
        description: "Your friendly neighborhood hero swings into action. Peter Parker balances life, love, and responsibility while facing iconic villains and everyday challenges.",
        published: "2023",
        pages: "260",
        language: "English",
        isbn: "978-3-16-148410-12",
        rating: "4.9",
        reviews: "152",
        badge: "available"
    },

    // Discover books (5–>24)
    {
        id: 5,
        img: "img/design-pattern.jpg",
        category: "Programming",
        title: "Design Patterns: Elements of Reusable Object-Oriented Software",
        author: "Erich Gamma",
        style: "architecture",
        status: "Available",
        description: "A foundational guide to object-oriented design patterns that has shaped generations of software architects and developers.",
        published: "1994",
        pages: "395",
        language: "English",
        isbn: "978-0-20-163361-0",
        rating: "4.8",
        reviews: "2.1K",
        badge: "available"
    },
    {
        id: 6,
        img: "img/brave-new-world.jpg",
        category: "Novel",
        title: "Brave New World",
        author: "Aldous Huxley",
        style: "sociology",
        status: "Available",
        description: "A dystopian social science fiction classic that explores a future of genetically engineered citizens, psychological manipulation, and enforced social harmony.",
        published: "1932",
        pages: "288",
        language: "English",
        isbn: "978-0-06-085052-4",
        rating: "4.5",
        reviews: "1.4K",
        badge: "available"
    },
    {
        id: 7,
        img: "img/the-incal.jpg",
        category: "Comic",
        title: "The Incal",
        author: "Alejandro Jodorowsky",
        style: "architecture",
        status: "Available",
        description: "A surreal science fiction graphic novel following a down-on-his-luck detective through a cosmic adventure of gods, aliens, and metaphysical forces.",
        published: "1981",
        pages: "308",
        language: "English",
        isbn: "978-1-59-465093-5",
        rating: "4.7",
        reviews: "320",
        badge: "available"
    },
    {
        id: 8,
        img: "img/the-sound-and-the-fury.jpg",
        category: "Literature",
        title: "The Sound and the Fury",
        author: "William Faulkner",
        style: "acoustics",
        status: "Available",
        description: "A landmark of American literature told through multiple narrators, capturing the decline of the Compson family in the American South.",
        published: "1929",
        pages: "336",
        language: "English",
        isbn: "978-0-67-973224-2",
        rating: "4.4",
        reviews: "540",
        badge: "available"
    },
    {
        id: 9,
        img: "img/the-structure-of scientiific-revolutions.jpg",
        category: "History",
        title: "The Structure of Scientific Revolutions",
        author: "Thomas S. Kuhn",
        style: "sociology",
        status: "Available",
        description: "One of the most influential books in the history of science, introducing the concept of paradigm shifts in scientific progress.",
        published: "1962",
        pages: "210",
        language: "English",
        isbn: "978-0-22-645812-0",
        rating: "4.6",
        reviews: "890",
        badge: "available"
    },
    {
        id: 10,
        img: "img/The Mythical Man-Month.jpg",
        category: "Programming",
        title: "The Mythical Man-Month",
        author: "Fred Brooks",
        style: "sociology",
        status: "Available",
        description: "Essays on software engineering and project management, famous for Brooks's law: adding manpower to a late software project makes it later.",
        published: "1975",
        pages: "322",
        language: "English",
        isbn: "978-0-20-183595-3",
        rating: "4.7",
        reviews: "1.1K",
        badge: "available"
    },
    {
        id: 11,
        img: "img/The-Pillars-of-the-Earth.jpg",
        category: "Novel",
        title: "The Pillars of the Earth",
        author: "Ken Follett",
        style: "architecture",
        status: "Available",
        description: "A sweeping historical novel centered on the building of a cathedral in 12th-century England, weaving together ambition, faith, and political intrigue.",
        published: "1989",
        pages: "806",
        language: "English",
        isbn: "978-0-45-116689-0",
        rating: "4.8",
        reviews: "1.7K",
        badge: "available"
    },
    {
        id: 12,
        img: "img/Transmetropolitan.jpg",
        category: "Comic",
        title: "Transmetropolitan",
        author: "Warren Ellis",
        style: "sociology",
        status: "Borrowed",
        description: "A gonzo journalist returns to a dystopian future city to fight corruption and abuse of power in this acclaimed cyberpunk comic series.",
        published: "1997",
        pages: "144",
        language: "English",
        isbn: "978-1-40-123455-7",
        rating: "4.6",
        reviews: "280",
        badge: "borrowed"
    },
    {
        id: 13,
        img: "img/Les-Misérables.jpg",
        category: "Literature",
        title: "Les Misérables",
        author: "Victor Hugo",
        style: "sociology",
        status: "Available",
        description: "A sweeping tale of justice, redemption, and revolution in 19th-century France, following the lives of ex-convict Jean Valjean and those he touches.",
        published: "1862",
        pages: "1,232",
        language: "English",
        isbn: "978-0-14-044430-8",
        rating: "4.9",
        reviews: "2.5K",
        badge: "available"
    },
    {
        id: 14,
        img: "img/The-Architecture-of-Happiness.jpg",
        category: "History",
        title: "The Architecture of Happiness",
        author: "Alain de Botton",
        style: "architecture",
        status: "Available",
        description: "A philosophical exploration of how architecture influences our emotions and sense of well-being, from ancient temples to modern homes.",
        published: "2006",
        pages: "280",
        language: "English",
        isbn: "978-0-30-727724-4",
        rating: "4.5",
        reviews: "430",
        badge: "available"
    },
    {
        id: 15,
        img: "img/Designing Data-Intensive Applications.jpg",
        category: "Programming",
        title: "Designing Data-Intensive Applications",
        author: "Martin Kleppmann",
        style: "architecture",
        status: "Available",
        description: "An in-depth guide to the principles and trade-offs behind scalable, reliable, and maintainable data systems.",
        published: "2017",
        pages: "616",
        language: "English",
        isbn: "978-1-44-937332-0",
        rating: "4.9",
        reviews: "1.3K",
        badge: "available"
    },
    {
        id: 16,
        img: "img/Foucault's Pendulum.jpg",
        category: "Novel",
        title: "Foucault's Pendulum",
        author: "Umberto Eco",
        style: "acoustics",
        status: "Available",
        description: "Three book editors invent a conspiracy theory for fun, only to find their fictional connections may be dangerously real.",
        published: "1988",
        pages: "641",
        language: "English",
        isbn: "978-0-15-132765-2",
        rating: "4.4",
        reviews: "380",
        badge: "available"
    },
    {
        id: 17,
        img: "img/Maus.jpg",
        category: "Comic",
        title: "Maus",
        author: "Art Spiegelman",
        style: "sociology",
        status: "Borrowed",
        description: "A Pulitzer Prize-winning graphic novel that portrays the Holocaust through the experiences of the author's father, depicted as mice and cats.",
        published: "1980",
        pages: "296",
        language: "English",
        isbn: "978-0-67-940641-9",
        rating: "4.9",
        reviews: "1.8K",
        badge: "borrowed"
    },
    {
        id: 18,
        img: "img/The Hunchback of Notre-Dame.jpg",
        category: "Literature",
        title: "The Hunchback of Notre-Dame",
        author: "Victor Hugo",
        style: "architecture",
        status: "Available",
        description: "A tragic tale of love, prejudice, and fate set against the towering backdrop of medieval Paris and Notre-Dame Cathedral.",
        published: "1831",
        pages: "528",
        language: "English",
        isbn: "978-0-14-044353-0",
        rating: "4.6",
        reviews: "620",
        badge: "available"
    },
    {
        id: 19,
        img: "img/The Soundscape.jpg",
        category: "History",
        title: "The Soundscape: Our Sonic Environment and the Tuning of the World",
        author: "R. Murray Schafer",
        style: "acoustics",
        status: "Available",
        description: "A pioneering study of acoustic ecology and how the sounds of our environment shape culture, communication, and consciousness.",
        published: "1977",
        pages: "301",
        language: "English",
        isbn: "978-0-89-281455-8",
        rating: "4.5",
        reviews: "210",
        badge: "available"
    },
    {
        id: 20,
        img: "img/Patterns of Enterprise Application Architecture.jpg",
        category: "Programming",
        title: "Patterns of Enterprise Application Architecture",
        author: "Martin Fowler",
        style: "architecture",
        status: "Available",
        description: "A comprehensive catalog of patterns for designing robust, scalable enterprise software systems.",
        published: "2002",
        pages: "533",
        language: "English",
        isbn: "978-0-32-112742-6",
        rating: "4.7",
        reviews: "760",
        badge: "available"
    },
    {
        id: 21,
        img: "img/1984.jpg",
        category: "Novel",
        title: "1984",
        author: "George Orwell",
        style: "sociology",
        status: "Borrowed",
        description: "A chilling dystopian novel about totalitarian surveillance, propaganda, and the erosion of truth in a society ruled by Big Brother.",
        published: "1949",
        pages: "328",
        language: "English",
        isbn: "978-0-45-152493-5",
        rating: "4.8",
        reviews: "3.2K",
        badge: "borrowed"
    },
    {
        id: 22,
        img: "img/Batman.jpg",
        category: "Comic",
        title: "Batman: Death by Design",
        author: "Chip Kidd",
        style: "architecture",
        status: "Available",
        description: "Batman investigates a series of construction accidents in Gotham in this stylish graphic novel blending superhero action with architectural design.",
        published: "2012",
        pages: "112",
        language: "English",
        isbn: "978-1-40-123464-9",
        rating: "4.4",
        reviews: "190",
        badge: "available"
    },
    {
        id: 23,
        img: "img/Chamber Music.jpg",
        category: "Literature",
        title: "Chamber Music",
        author: "James Joyce",
        style: "acoustics",
        status: "Available",
        description: "A collection of lyrical love poems and witty wordplay from one of the twentieth century's most innovative writers.",
        published: "1907",
        pages: "96",
        language: "English",
        isbn: "978-0-14-042204-7",
        rating: "4.3",
        reviews: "150",
        badge: "available"
    },
    {
        id: 24,
        img: "img/The Division of Labor in Society.jpg",
        category: "History",
        title: "The Division of Labor in Society",
        author: "Émile Durkheim",
        style: "sociology",
        status: "Available",
        description: "A foundational sociological text examining how social solidarity evolves as labor becomes increasingly specialized in modern societies.",
        published: "1893",
        pages: "272",
        language: "English",
        isbn: "978-0-68-483632-5",
        rating: "4.5",
        reviews: "260",
        badge: "available"
    },

    // Additional books from categories.html (25–>40)
    {
        id: 25,
        img: "img/Rise and Fall of Empires.jpg",
        category: "History",
        title: "Rise and Fall of Empires",
        author: "Paul Kennedy",
        style: "sociology",
        status: "Not Available",
        description: "A sweeping historical analysis exploring the economic and military forces that have driven the rise and decline of great powers across centuries.",
        published: "1987",
        pages: "704",
        language: "English",
        isbn: "978-0-39-475372-2",
        rating: "4.7",
        reviews: "540",
        badge: "not-available"
    },
    {
        id: 26,
        img: "img/The Silent Canvas.jpg",
        category: "Novel",
        title: "The Silent Canvas",
        author: "Linda S. Gunther",
        style: "architecture",
        status: "Available",
        description: "A moving novel about an artist who loses her voice and must find new ways to express truth, beauty, and grief through her paintings.",
        published: "2015",
        pages: "342",
        language: "English",
        isbn: "978-1-50-394221-8",
        rating: "4.4",
        reviews: "180",
        badge: "available"
    },
    {
        id: 27,
        img: "img/Angkorian Structures.jpg",
        category: "History",
        title: "Angkorian Structures",
        author: "George Cœdès",
        style: "architecture",
        status: "Up Coming",
        description: "A richly illustrated study of the temples, hydraulics, and urban planning of the ancient Khmer Empire centered at Angkor.",
        published: "2024",
        pages: "256",
        language: "English",
        isbn: "978-9-81-142233-4",
        rating: "4.8",
        reviews: "95",
        badge: "up-coming"
    },
    {
        id: 28,
        img: "img/Shadows of the Past.jpg",
        category: "Literature",
        title: "Shadows of the Past",
        author: "Margaret Harwood",
        style: "sociology",
        status: "Not Available",
        description: "A literary novel about memory, family secrets, and the long shadows cast by choices made in youth.",
        published: "2011",
        pages: "288",
        language: "English",
        isbn: "978-0-06-199895-0",
        rating: "4.3",
        reviews: "120",
        badge: "not-available"
    },
    {
        id: 29,
        img: "img/Mastering JavaScript.jpg",
        category: "Programming",
        title: "Mastering JavaScript",
        author: "Ved Antani",
        style: "acoustics",
        status: "Available",
        description: "A deep dive into advanced JavaScript concepts, patterns, and best practices for experienced developers.",
        published: "2016",
        pages: "300",
        language: "English",
        isbn: "978-1-78-588-359-6",
        rating: "4.5",
        reviews: "410",
        badge: "available"
    },
    {
        id: 30,
        img: "img/Echoes in the Wind.jpg",
        category: "Literature",
        title: "Echoes in the Wind",
        author: "Julia Butler",
        style: "architecture",
        status: "Available",
        description: "A lyrical literary novel set in a windswept coastal town, where past tragedies echo through generations of a fractured family.",
        published: "2019",
        pages: "364",
        language: "English",
        isbn: "978-1-54-204221-7",
        rating: "4.6",
        reviews: "230",
        badge: "available"
    },
    {
        id: 31,
        img: "img/The Midnight Code.jpg",
        category: "Novel",
        title: "The Midnight Code",
        author: "Michael Erbschloe",
        style: "sociology",
        status: "Available",
        description: "A tech-thriller about a cybersecurity analyst who uncovers a conspiracy hidden inside a string of midnight data breaches.",
        published: "2020",
        pages: "312",
        language: "English",
        isbn: "978-1-49-208110-2",
        rating: "4.2",
        reviews: "140",
        badge: "available"
    },
    {
        id: 32,
        img: "img/Python & Sound Systems.jpg",
        category: "Programming",
        title: "Python & Sound Systems",
        author: "Allen B. Downey",
        style: "acoustics",
        status: "Up Coming",
        description: "An accessible introduction to digital signal processing and audio programming using Python.",
        published: "2024",
        pages: "280",
        language: "English",
        isbn: "978-1-49-207782-2",
        rating: "4.7",
        reviews: "88",
        badge: "up-coming"
    },
    {
        id: 33,
        img: "img/Starlight Sonata.webp",
        category: "Literature",
        title: "Starlight Sonata",
        author: "Sophea Reaksa",
        style: "architecture",
        status: "Not Available",
        description: "A poetic literary work weaving music, memory, and starlight into a meditation on love and loss.",
        published: "2022",
        pages: "240",
        language: "English",
        isbn: "978-9-81-183322-2",
        rating: "4.5",
        reviews: "105",
        badge: "not-available"
    },
    {
        id: 34,
        img: "img/Modern Cultural Shifts.jpg",
        category: "History",
        title: "Modern Cultural Shifts",
        author: "Sok Chanleap",
        style: "sociology",
        status: "Available",
        description: "A contemporary exploration of how technology, migration, and media are reshaping culture and identity in the modern world.",
        published: "2021",
        pages: "288",
        language: "English",
        isbn: "978-0-14-313428-5",
        rating: "4.4",
        reviews: "170",
        badge: "available"
    },
    {
        id: 35,
        img: "img/Beyond the Horizon.jpg",
        category: "Novel",
        title: "Beyond the Horizon",
        author: "Eugene O'Neill",
        style: "architecture",
        status: "Not Available",
        description: "A powerful family tragedy about two brothers whose dreams of escape are crushed by the realities of the land and sea.",
        published: "1918",
        pages: "176",
        language: "English",
        isbn: "978-0-30-680590-8",
        rating: "4.6",
        reviews: "210",
        badge: "not-available"
    },
    {
        id: 36,
        img: "img/Architecting Web Apps.jpg",
        category: "Programming",
        title: "Architecting Web Apps",
        author: "Dino Esposito",
        style: "architecture",
        status: "Up Coming",
        description: "A practical guide to designing scalable, secure, and maintainable web applications for modern cloud environments.",
        published: "2024",
        pages: "420",
        language: "English",
        isbn: "978-0-13-816809-1",
        rating: "4.5",
        reviews: "72",
        badge: "up-coming"
    },
    {
        id: 37,
        img: "img/Songs of the Acoustic Soul.jpg",
        category: "Literature",
        title: "Songs of the Acoustic Soul",
        author: "Sophanha",
        style: "acoustics",
        status: "Available",
        description: "A lyrical collection of stories and poems inspired by music, silence, and the rhythm of everyday life.",
        published: "2020",
        pages: "210",
        language: "English",
        isbn: "978-9-81-145678-1",
        rating: "4.3",
        reviews: "130",
        badge: "available"
    },
    {
        id: 38,
        img: "img/The Grand Blueprint.jpg",
        category: "History",
        title: "The Grand Blueprint",
        author: "Robert A.M. Stern",
        style: "architecture",
        status: "Available",
        description: "A sweeping history of architecture and urbanism, tracing the grand designs that have shaped human civilization.",
        published: "2018",
        pages: "512",
        language: "English",
        isbn: "978-1-58-093511-6",
        rating: "4.7",
        reviews: "190",
        badge: "available"
    },
    {
        id: 39,
        img: "img/Whispers of the Deep.jpg",
        category: "Novel",
        title: "Whispers of the Deep",
        author: "Rangsey",
        style: "sociology",
        status: "Not Available",
        description: "A haunting novel of mystery and memory set along the banks of an ancient river, where voices from the past refuse to be silenced.",
        published: "2023",
        pages: "334",
        language: "English",
        isbn: "978-9-81-178899-8",
        rating: "4.4",
        reviews: "115",
        badge: "not-available"
    },
    {
        id: 40,
        img: "img/Gotham Infrastructure.jpg",
        category: "Comic",
        title: "Gotham Infrastructure",
        author: "Lucius Fox",
        style: "architecture",
        status: "Not Available",
        description: "A behind-the-scenes comic look at the engineering marvels that power Gotham City and support its most famous protector.",
        published: "2023",
        pages: "188",
        language: "English",
        isbn: "978-1-40-129988-4",
        rating: "4.5",
        reviews: "160",
        badge: "not-available"
    }
];
